### ISSUE TITLE
Does not render admonition with colored boxes

### ISSUE THREAD

**Issue by kloudwrangler** [maxnegro/joplin-plugin-admonition#1]
I installed the plugin and tried the following:

```md
!!! bug This is a bug
This is the body of the bug
!!!
```
This rendered the text without a box around it

![image](https://user-images.githubusercontent.com/15901900/123988643-6b5bfb00-d985-11eb-9dd5-79a4b5b8ee65.png)

Joplin 2.1.7 (prod, darwin)

Client ID: a0be3709ddb64dc19b4ecce90de3eac5
Sync Version: 2
Profile Version: 39
Keychain Supported: Yes

Revision: 04c4015

**Comment by maxnegro** [comment]
Uhm. I'm unable to reproduce and I see others are using it. Are you sure you enabled the plugin in Tools/Options/Plugins ?

**Comment by kloudwrangler** [comment]
@maxnegro I was actually able to use the plugin now. I am not sure why at the time this wouldn't work but it is now working, it just renders unreadable in dark mode though.

**Comment by maxnegro** [comment]
> it just renders unreadable in dark mode though.

@aldorperez1 Yes, I still haven't addressed this problem. See #2
