### ISSUE TITLE
Does not render admonition with themes

### ISSUE THREAD

**Issue by jsantos74** [maxnegro/joplin-plugin-admonition#2]
If you use the light them it works OK.
![image](https://user-images.githubusercontent.com/52458373/124100019-fdcbcf80-da55-11eb-8530-bae4b7ece3d9.png)
![image](https://user-images.githubusercontent.com/52458373/124100063-0a502800-da56-11eb-830c-ba820159ce4c.png)

But if you use the Dark theme 
![image](https://user-images.githubusercontent.com/52458373/124100313-484d4c00-da56-11eb-937e-bfed8ebb369f.png)
![image](https://user-images.githubusercontent.com/52458373/124100356-513e1d80-da56-11eb-9e66-592d7e024494.png)

Joplin 2.1.7 (prod, linux)
Client ID: ac59218bf3454049b9bfb0a2f478dcfc
Sync Version: 2
Profile Version: 39
Keychain Supported: No
Revision: 04c4015

**Comment by robertoszek** [comment]
For now I just manually edited this line on the `markdownit-admonition.css` file on the .jpl archive:
https://github.com/maxnegro/joplin-plugin-admonition/blob/7083d34096a8fff31a1b3b401f27cc1fc5653569/src/markdownit-admonition.css#L2
to
```css
  background-color: transparent;
```
and reinstalled the plugin with the modified .jpl file.

Good enough for me and the dark theme I'm using.

**Comment by maxnegro** [comment]
> ```css
>   background-color: transparent;
> ```

Nice catch. I'll add it to next release, in a week or so.
