### ISSUE TITLE
Random Characters in Title

### ISSUE THREAD

**Issue by esmoyer** [maxnegro/joplin-plugin-admonition#7]
This plugin was working just great, but then yesterday I noticed that the title now has weird characters prepended to it. This happens no matter what type I use and on different notes and notebooks as well as different computers. I am on the pre-release 2.9.2 testing out the new PDF render-er; so I might try to move back to the stable version and see if that resolves it.

![image](https://user-images.githubusercontent.com/17444085/185224055-f99a7d94-78f3-4056-a61e-842c29885018.png)

**Comment by esmoyer** [comment]
Yep, that was it. Apparently the pre-release doesn't like the little images based on the admonition type

![image](https://user-images.githubusercontent.com/17444085/185224750-4b1781a6-55aa-4740-825f-0e73a5a2ee73.png)

**Comment by maxnegro** [comment]
> Yep, that was it. Apparently the pre-release doesn't like the little images based on the admonition type

Thank you nonetheless for the feedback. I think I should address this before next release.

**Comment by sepremento** [comment]
I am also experiencing this issue on Joplin v2.14.20. After restarting Joplin the issue disappears, but returns after some time. I haven't figured out yet what causes this issue, so just reporting.

![bug-in-admonition-plugin](https://github.com/maxnegro/joplin-plugin-admonition/assets/28418936/33d5e934-d235-4315-bd25-6f956d041b7a)
